### ISSUE TITLE
oh-my-poshバージョンV3によるpwshでのエラーについて

### ISSUE THREAD

**Issue by kuni3933** [tadashi-aikawa/owl-playbook#2]
oh-my-poshのバージョンが最新のV3だと、owl-playbook/mnt/windows/power-shell/Microsoft.PowerShell_profile.ps1の33~47行目、
すなわちoh-myposh関連のコードでエラーが発生してしまいます。
どのエラーも「このオブジェクトではプロパティが見つからない」というものです。
https://ohmyposh.dev/docs/upgrading/

**Comment by tadashi-aikawa** [comment]
ご報告ありがとうございます！

oh-my-poshをバージョンアップしたときに対応してみます 👍

**Comment by tadashi-aikawa** [comment]
以下のコミットでv3に対応しました。

https://github.com/tadashi-aikawa/owl-playbook/commit/2986ddb1044026d2af22c2b06aca81e702b0796c
